from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class LoginResponse(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, benutzername=None, rolle=None):  # noqa: E501
        """LoginResponse - a model defined in OpenAPI

        :param benutzername: The benutzername of this LoginResponse.  # noqa: E501
        :type benutzername: str
        :param rolle: The rolle of this LoginResponse.  # noqa: E501
        :type rolle: str
        """
        self.openapi_types = {
            'benutzername': str,
            'rolle': str
        }

        self.attribute_map = {
            'benutzername': 'benutzername',
            'rolle': 'rolle'
        }

        self._benutzername = benutzername
        self._rolle = rolle

    @classmethod
    def from_dict(cls, dikt) -> 'LoginResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The LoginResponse of this LoginResponse.  # noqa: E501
        :rtype: LoginResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def benutzername(self) -> str:
        """Gets the benutzername of this LoginResponse.


        :return: The benutzername of this LoginResponse.
        :rtype: str
        """
        return self._benutzername

    @benutzername.setter
    def benutzername(self, benutzername: str):
        """Sets the benutzername of this LoginResponse.


        :param benutzername: The benutzername of this LoginResponse.
        :type benutzername: str
        """

        self._benutzername = benutzername

    @property
    def rolle(self) -> str:
        """Gets the rolle of this LoginResponse.


        :return: The rolle of this LoginResponse.
        :rtype: str
        """
        return self._rolle

    @rolle.setter
    def rolle(self, rolle: str):
        """Sets the rolle of this LoginResponse.


        :param rolle: The rolle of this LoginResponse.
        :type rolle: str
        """

        self._rolle = rolle
