from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class RegisterRequest(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, benutzername=None, passwort=None, rolle=None):  # noqa: E501
        """RegisterRequest - a model defined in OpenAPI

        :param benutzername: The benutzername of this RegisterRequest.  # noqa: E501
        :type benutzername: str
        :param passwort: The passwort of this RegisterRequest.  # noqa: E501
        :type passwort: str
        :param rolle: The rolle of this RegisterRequest.  # noqa: E501
        :type rolle: str
        """
        self.openapi_types = {
            'benutzername': str,
            'passwort': str,
            'rolle': str
        }

        self.attribute_map = {
            'benutzername': 'benutzername',
            'passwort': 'passwort',
            'rolle': 'rolle'
        }

        self._benutzername = benutzername
        self._passwort = passwort
        self._rolle = rolle

    @classmethod
    def from_dict(cls, dikt) -> 'RegisterRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The RegisterRequest of this RegisterRequest.  # noqa: E501
        :rtype: RegisterRequest
        """
        return util.deserialize_model(dikt, cls)

    @property
    def benutzername(self) -> str:
        """Gets the benutzername of this RegisterRequest.


        :return: The benutzername of this RegisterRequest.
        :rtype: str
        """
        return self._benutzername

    @benutzername.setter
    def benutzername(self, benutzername: str):
        """Sets the benutzername of this RegisterRequest.


        :param benutzername: The benutzername of this RegisterRequest.
        :type benutzername: str
        """
        if benutzername is None:
            raise ValueError("Invalid value for `benutzername`, must not be `None`")  # noqa: E501

        self._benutzername = benutzername

    @property
    def passwort(self) -> str:
        """Gets the passwort of this RegisterRequest.


        :return: The passwort of this RegisterRequest.
        :rtype: str
        """
        return self._passwort

    @passwort.setter
    def passwort(self, passwort: str):
        """Sets the passwort of this RegisterRequest.


        :param passwort: The passwort of this RegisterRequest.
        :type passwort: str
        """
        if passwort is None:
            raise ValueError("Invalid value for `passwort`, must not be `None`")  # noqa: E501

        self._passwort = passwort

    @property
    def rolle(self) -> str:
        """Gets the rolle of this RegisterRequest.


        :return: The rolle of this RegisterRequest.
        :rtype: str
        """
        return self._rolle

    @rolle.setter
    def rolle(self, rolle: str):
        """Sets the rolle of this RegisterRequest.


        :param rolle: The rolle of this RegisterRequest.
        :type rolle: str
        """
        allowed_values = ["User", "Admin"]  # noqa: E501
        if rolle not in allowed_values:
            raise ValueError(
                "Invalid value for `rolle` ({0}), must be one of {1}"
                .format(rolle, allowed_values)
            )

        self._rolle = rolle
