openapi: 3.0.1
info:
  description: "REST API für Login, Registrierung und Spielinteraktion"
  title: ProphetPlay API
  version: 1.0.0

servers:
  - description: Lokale Entwicklungsumgebung
    url: http://localhost:8080

paths:
  /api/benutzer/register:
    post:
      summary: Registrierung eines neuen Benutzers
      operationId: openapi_server.controllers.default_controller.api_benutzer_register_post
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegisterRequest'
      responses:
        "200": { description: Registrierung erfolgreich }
        "409": { description: Benutzername existiert bereits }
        "500": { description: Serverfehler }

  /api/benutzer/login:
    post:
      summary: Login eines Benutzers
      operationId: openapi_server.controllers.default_controller.api_benutzer_login_post
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
      responses:
        "200":
          description: Login erfolgreich
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoginResponse'
        "401": { description: Ungültige Anmeldedaten }
        "500": { description: Serverfehler }

  /api/benutzer/liste:
    get:
      summary: Liste aller Benutzer (nur Admin)
      operationId: openapi_server.controllers.default_controller.api_benutzer_liste_get
      parameters:
        - name: requester
          in: query
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Benutzerliste
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
        "403": { description: Nicht autorisiert }
        "500": { description: Serverfehler }

  /api/benutzer/loeschen:
    delete:
      summary: Benutzer löschen (nur Admin)
      operationId: openapi_server.controllers.default_controller.api_benutzer_loeschen_delete
      parameters:
        - name: requester
          in: query
          required: true
          schema:
            type: string
        - name: target
          in: query
          required: true
          schema:
            type: string
      responses:
        "200": { description: Benutzer gelöscht }
        "403": { description: Nicht autorisiert }
        "500": { description: Serverfehler }


components:
  schemas:
    RegisterRequest:
      type: object
      required: [benutzername, passwort, role_id]
      properties:
        benutzername:
          type: string
        passwort:
          type: string
        role_id:
          type: integer
    LoginRequest:
      type: object
      required: [benutzername, passwort]
      properties:
        benutzername:
          type: string
        passwort:
          type: string
    LoginResponse:
      type: object
      properties:
        benutzername:
          type: string
        rolle:
          type: string