openapi: 3.0.1
info:
  description: "REST API für Login, Registrierung und Spielinteraktion"
  title: ProphetPlay API
  version: 1.0.0

servers:
  - description: Lokale Entwicklungsumgebung
    url: http://localhost:8080

paths:
  /api/benutzer/login:
    post:
      summary: Login eines Benutzers
      operationId: openapi_server.controllers.default_controller.api_benutzer_login_post
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
      responses:
        "200":
          description: Login erfolgreich
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoginResponse'
        "401":
          description: Ungültige Anmeldedaten

  /api/benutzer/register:
    post:
      summary: Registrierung eines neuen Benutzers
      operationId: openapi_server.controllers.default_controller.api_benutzer_register_post
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegisterRequest'
      responses:
        "200":
          description: Registrierung erfolgreich
        "409":
          description: Benutzername existiert bereits

components:
  schemas:
    LoginRequest:
      type: object
      required: [benutzername, passwort]
      properties:
        benutzername:
          type: string
        passwort:
          type: string

    RegisterRequest:
      type: object
      required: [benutzername, passwort, rolle]
      properties:
        benutzername:
          type: string
        passwort:
          type: string
        rolle:
          type: string
          enum: [User, Admin]

    LoginResponse:
      type: object
      properties:
        benutzername:
          type: string
        rolle:
          type: string
